packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Vue
  "vue": "^3.5.13"
  "pinia": "^3.0.2"
  "vue-router": "^4.5.1"
  "vue-tsc": "^2.2.10"
  "vite-plugin-vue-devtools": "^7.7.6"
  "vee-validate": "4.15.0"
  "run-p": "^0.0.0"
  "npm-run-all": "^4.1.5"
  "@vue/tsconfig": "^0.7.0"

  # Prime vue
  "primevue": "^4.3.4"
  "@primeuix/themes": "^1.1.1"
  "@primevue/core": "^4.3.4"
  "primeicons": "^7.0.0"
  "flatpickr": "^4.6.13"

  # Vue ui
  "qalendar": "3.7.0"
  "quill": "2.0.3"

  # Eslint
  "eslint": "^9.26.0"
  "eslint-plugin-vue": "^10.1.0"
  "prettier": "^3.5.3"

  # Vite
  "vitepress": "^1.6.3"
  "vite": "^6.3.5"

  # TypeScript
  "typescript": "~5.8.3"
  "@tsconfig/node22": "^22.0.1"
  "@types/node": "^22.15.17"
  "ts-node": "^10.9.2"
  "ts-loader": "^9.5.2"

  # Тестирование
  "vitest": "^3.1.3"
  "yup": "1.6.1"
  "zod": "^3.24.4"
  "playwright": "^1.52.0"
  "@playwright/test": "^1.2.12"
  "vitest-browser-vue": "^0.2.0"
  "@vitejs/plugin-vue": "^5.2.4"
  "@vitest/browser": "^3.1.3"
  "@vue/test-utils": "^2.4.6"
  "supertest": "^7.1.0"
  "@types/supertest": "^6.0.3"
  "@faker-js/faker": "^9.7.0"
  "@vitest/coverage-v8": "^3.1.3"
  "unplugin-swc": "^1.5.2"
  "@swc/core": "^1.11.24"

  # Nest
  "@nestjs/common": "^11.1.0"
  "@nestjs/core": "^11.1.0"
  "@nestjs/jwt": "^11.0.0"
  "@nestjs/mapped-types": "^2.1.0"
  "@nestjs/platform-express": "^11.1.0"
  "@nestjs/swagger": "^11.2.0"
  "@nestjs/cli": "^11.0.7"
  "@nestjs/schematics": "^11.0.5"
  "@nestjs/testing": "^11.1.0"
  "@types/express": "^5.0.1"
  "express": "^5.1.0"

  # Nest пакеты
  "class-transformer": "^0.5.1"
  "class-validator": "^0.14.2"
  "cookie-parser": "^1.4.7"
  "@types/cookie-parser": "^1.4.8"
  "dotenv": "^16.5.0"
  "pizzip": "^3.1.8"

  # Prisma
  "prisma": "^6.7.0"
  "@prisma/client": "^6.7.0"

  # File generators
  "docxtemplater": "^3.61.2"

  # Работа с датами
  "moment": "^2.30.1"
  "moment-timezone": "^0.5.48"

  # Telegram
  "grammy": "^1.36.1"
  "@grammyjs/hydrate": "^1.4.1"