packages:
  - "apps/*"
  - "packages/*"

catalog:
  vitepress: "^1.6.3"
  vue: "^3.5.13"
  pinia: "^3.0.2"
  vue-router: "^4.5.0"
  zod: "^3.24.3"
  typescript: "~5.7.3"
  prettier: "^3.4.2"
  vite: "^6.0.11"
  vue-tsc: "^2.2.0"
  eslint-plugin-vue: "^9.32.0"
  vitest: "^3.1.2"
  faker: "^6.6.6"



