packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Vue
  "vue": "^3.5.13"
  "pinia": "^3.0.2"
  "vue-router": "^4.5.0"
  "vue-tsc": "^2.2.0"
  "vite-plugin-vue-devtools": "^7.6.8"
  "vee-validate": "4.13.2"
  "run-p": "^0.0.0"
  "npm-run-all": "^4.1.5"
  "@vue/tsconfig": "^0.7.0"

  # Prime vue
  "primevue": "^4.3.4"
  "@primeuix/themes": "^1.1.1"
  "@primevue/core": "^4.3.4"
  "primeicons": "^7.0.0"
  "flatpickr": "^4.6.13"

  # Vue ui
  "qalendar": "3.7.0"
  "quill": "1.3.7"
  "sass": "^1.83.4"

  # Eslint
  "eslint": "^9.26.0"
  "eslint-plugin-vue": "^9.32.0"
  "prettier": "^3.4.2"

  # Vite
  "vitepress": "^1.6.3"
  "vite": "^6.0.11"

  # TypeScript
  "typescript": "~5.7.3"
  "@tsconfig/node22": "^22.0.0"
  "@types/node": "^22.10.2"
  "ts-node": "^10.9.1"
  "ts-loader": "^9.4.3"

  # Тестирование
  "vitest": "^3.1.2"
  "faker": "^6.6.6"
  "yup": "1.4.0"
  "zod": "^3.24.3"
  "playwright": "^1.52.0"
  "@playwright/test": "^1.52.0"
  "vitest-browser-vue": "^0.2.0"
  "@vitejs/plugin-vue": "^5.2.3"
  "@vitest/browser": "^3.1.2"
  "@vue/test-utils": "^2.4.6"
  "jest": "^29.5.0"
  "supertest": "^7.1.0"
  "@types/supertest": "^6.0.0"
  "ts-jest": "^29.1.0"
  "@types/jest": "^29.5.2"
  "@faker-js/faker": "^8.4.1"

  # Nest
  "@nestjs/common": "^10.0.0"
  "@nestjs/core": "^10.0.0"
  "@nestjs/jwt": "^10.2.0"
  "@nestjs/mapped-types": "*"
  "@nestjs/platform-express": "^10.0.0"
  "@nestjs/swagger": "^7.3.1"
  "@nestjs/cli": "^10.0.0"
  "@nestjs/schematics": "^10.0.0"
  "@nestjs/testing": "^10.0.0"
  "@types/express": "^4.17.17"

  # Nest пакеты
  "class-transformer": "^0.5.1"
  "class-validator": "^0.14.1"
  "cookie-parser": "^1.4.6"
  "@types/cookie-parser": "^1.4.7"
  "sql-formatter": "^15.4.3"
  "dotenv": "^16.4.5"
  "pizzip": "^3.1.7"
  "tsconfig-paths": "^4.2.0"

  # Prisma
  "prisma": "^6.3.1"
  "@prisma/client": "^6.3.1"

  # File generators
  "docx": "8.5.0"
  "docxtemplater": "^3.55.4"

  # Работа с датами
  "moment": "^2.30.1"
  "moment-timezone": "^0.5.47"

  # Telegram
  "grammy": "^1.34.1"
  "@grammyjs/hydrate": "^1.4.1"